// GENERATED by scripts/generate-design-tokens.mjs — edit tokens.css, not this file.
// Source of truth: design-mocks/living-companion/tokens.css (light) and
// tokens-dark.css (dark). Colours are the mock's oklch declarations pushed
// through OKLCH → OKLab → LMS → linear sRGB → gamma, clamped to gamut where
// noted; spacing and radii are rem × 16pt; durations are ms → seconds.
// Regenerate with `npm run tokens:build`.
import SwiftUI

enum DesignTokens {
    enum Light {
        static let paper = Color(red: 0.9755, green: 0.9510, blue: 0.9147, opacity: 1)
        static let paper2 = Color(red: 0.9515, green: 0.9164, blue: 0.8719, opacity: 1)
        static let paper3 = Color(red: 0.9285, green: 0.8814, blue: 0.8299, opacity: 1)
        static let paper4 = Color(red: 0.8999, green: 0.8398, blue: 0.7828, opacity: 1)
        static let ink = Color(red: 0.2093, green: 0.1269, blue: 0.1013, opacity: 1)
        static let ink2 = Color(red: 0.3213, green: 0.2374, blue: 0.2142, opacity: 1)
        static let inkStrong = Color(red: 0.0758, green: 0.0198, blue: 0.0095, opacity: 1)
        static let muted = Color(red: 0.4165, green: 0.3351, blue: 0.3069, opacity: 1)
        static let neutral = Color(red: 0.5220, green: 0.4510, blue: 0.4186, opacity: 1)
        static let rule = Color(red: 0.8322, green: 0.7686, blue: 0.7160, opacity: 1)
        static let rule2 = Color(red: 0.8874, green: 0.8430, blue: 0.7979, opacity: 1)
        static let accent = Color(red: 0.7306, green: 0.2921, blue: 0.2996, opacity: 1)
        static let accentStrong = Color(red: 0.6317, green: 0.1828, blue: 0.2069, opacity: 1)
        static let accentSoft = Color(red: 0.8822, green: 0.6525, blue: 0.6341, opacity: 1)
        static let accentInk = Color(red: 0.9854, green: 0.9723, blue: 0.9511, opacity: 1)
        static let focus = Color(red: 0.5919, green: 0.1423, blue: 0.1750, opacity: 1)
        static let calm = Color(red: 0.2177, green: 0.4660, blue: 0.3788, opacity: 1)
        static let calmSoft = Color(red: 0.7301, green: 0.8710, blue: 0.8014, opacity: 1)
        static let danger = Color(red: 0.6272, green: 0.2524, blue: 0.2022, opacity: 1)
        static let dangerInk = Color(red: 0.9953, green: 0.9668, blue: 0.9616, opacity: 1)
        static let veil = Color(red: 0.9883, green: 0.9719, blue: 0.9454, opacity: 0.6)
        static let veilAlpha: Double = 0.6
        static let veilStrong = Color(red: 0.9920, green: 0.9788, blue: 0.9576, opacity: 0.82)
        static let veilStrongAlpha: Double = 0.82
        static let veilEdge = Color(red: 0.6303, green: 0.4901, blue: 0.4309, opacity: 0.3)
        static let veilEdgeAlpha: Double = 0.3
        static let scrim = Color(red: 0.2320, green: 0.1600, blue: 0.1349, opacity: 0.4)
        static let scrimAlpha: Double = 0.4
        static let shadow = Color(red: 0.3683, green: 0.2131, blue: 0.1709, opacity: 0.16)
        static let shadowAlpha: Double = 0.16
        static let shadowDeep = Color(red: 0.3013, green: 0.1511, blue: 0.1165, opacity: 0.24)
        static let shadowDeepAlpha: Double = 0.24
        static let selection = Color(red: 0.7306, green: 0.2921, blue: 0.2996, opacity: 0.13)
        static let selectionAlpha: Double = 0.13
        static let noise = Color(red: 0.4302, green: 0.2977, blue: 0.2516, opacity: 0.05)
        static let noiseAlpha: Double = 0.05
        static let fieldRose = Color(red: 0.9479, green: 0.7128, blue: 0.7080, opacity: 1)
        static let fieldRoseFaint = Color(red: 0.9479, green: 0.7128, blue: 0.7080, opacity: 0.55)
        static let fieldRoseFaintAlpha: Double = 0.55
        static let fieldApricot = Color(red: 0.9890, green: 0.8044, blue: 0.6473, opacity: 1)
        static let fieldApricotFaint = Color(red: 0.9890, green: 0.8044, blue: 0.6473, opacity: 0.55)
        static let fieldApricotFaintAlpha: Double = 0.55
        static let fieldLavender = Color(red: 0.8268, green: 0.7775, blue: 0.9300, opacity: 1)
        static let fieldLavenderFaint = Color(red: 0.8268, green: 0.7775, blue: 0.9300, opacity: 0.5)
        static let fieldLavenderFaintAlpha: Double = 0.5
        static let fieldSage = Color(red: 0.7092, green: 0.8789, blue: 0.7893, opacity: 1)
        static let fieldSageFaint = Color(red: 0.7092, green: 0.8789, blue: 0.7893, opacity: 0.55)
        static let fieldSageFaintAlpha: Double = 0.55
        static let fieldGold = Color(red: 0.9423, green: 0.8711, blue: 0.7010, opacity: 1)
    }

    enum Dark {
        static let paper = Color(red: 0.1147, green: 0.0761, blue: 0.0612, opacity: 1)
        static let paper2 = Color(red: 0.1456, green: 0.1019, blue: 0.0834, opacity: 1)
        static let paper3 = Color(red: 0.1774, green: 0.1287, blue: 0.1061, opacity: 1)
        static let paper4 = Color(red: 0.2100, green: 0.1563, blue: 0.1294, opacity: 1)
        static let ink = Color(red: 0.9258, green: 0.8912, blue: 0.8398, opacity: 1)
        static let ink2 = Color(red: 0.8289, green: 0.7872, blue: 0.7342, opacity: 1)
        static let inkStrong = Color(red: 0.9825, green: 0.9650, blue: 0.9390, opacity: 1)
        static let muted = Color(red: 0.7096, green: 0.6609, blue: 0.6075, opacity: 1)
        static let neutral = Color(red: 0.5944, green: 0.5375, blue: 0.4937, opacity: 1)
        static let rule = Color(red: 0.2615, green: 0.2054, blue: 0.1774, opacity: 1)
        static let rule2 = Color(red: 0.2041, green: 0.1584, blue: 0.1374, opacity: 1)
        static let accent = Color(red: 0.8667, green: 0.4623, blue: 0.4286, opacity: 1)
        static let accentStrong = Color(red: 0.9384, green: 0.5435, blue: 0.4941, opacity: 1)
        static let accentSoft = Color(red: 0.3862, green: 0.1972, blue: 0.1874, opacity: 1)
        static let accentInk = Color(red: 0.1073, green: 0.0521, blue: 0.0429, opacity: 1)
        static let focus = Color(red: 0.8938, green: 0.4865, blue: 0.4518, opacity: 1)
        static let calm = Color(red: 0.4085, green: 0.6568, blue: 0.5624, opacity: 1)
        static let calmSoft = Color(red: 0.1184, green: 0.2249, blue: 0.1777, opacity: 1)
        static let danger = Color(red: 0.7591, green: 0.4138, blue: 0.3599, opacity: 1)
        static let dangerInk = Color(red: 0.0821, green: 0.0391, blue: 0.0322, opacity: 1)
        static let veil = Color(red: 0.1331, green: 0.0941, blue: 0.0777, opacity: 0.6)
        static let veilAlpha: Double = 0.6
        static let veilStrong = Color(red: 0.1114, green: 0.0776, blue: 0.0633, opacity: 0.82)
        static let veilStrongAlpha: Double = 0.82
        static let veilEdge = Color(red: 0.7314, green: 0.6183, blue: 0.5620, opacity: 0.3)
        static let veilEdgeAlpha: Double = 0.3
        static let scrim = Color(red: 0.0461, green: 0.0150, blue: 0.0085, opacity: 0.5)
        static let scrimAlpha: Double = 0.5
        static let shadow = Color(red: 0.0179, green: 0.0031, blue: 0.0013, opacity: 0.34)
        static let shadowAlpha: Double = 0.34
        static let shadowDeep = Color(red: 0.0094, green: 0.0007, blue: 0.0001, opacity: 0.5)
        static let shadowDeepAlpha: Double = 0.5
        static let selection = Color(red: 0.8667, green: 0.4623, blue: 0.4286, opacity: 0.2)
        static let selectionAlpha: Double = 0.2
        static let noise = Color(red: 0.7780, green: 0.7034, blue: 0.6458, opacity: 0.05)
        static let noiseAlpha: Double = 0.05
        static let fieldRose = Color(red: 0.4425, green: 0.2858, blue: 0.2844, opacity: 1)
        static let fieldRoseFaint = Color(red: 0.4425, green: 0.2858, blue: 0.2844, opacity: 0.55)
        static let fieldRoseFaintAlpha: Double = 0.55
        static let fieldApricot = Color(red: 0.4636, green: 0.3370, blue: 0.2255, opacity: 1)
        static let fieldApricotFaint = Color(red: 0.4636, green: 0.3370, blue: 0.2255, opacity: 0.55)
        static let fieldApricotFaintAlpha: Double = 0.55
        static let fieldLavender = Color(red: 0.3596, green: 0.3237, blue: 0.4306, opacity: 1)
        static let fieldLavenderFaint = Color(red: 0.3596, green: 0.3237, blue: 0.4306, opacity: 0.5)
        static let fieldLavenderFaintAlpha: Double = 0.5
        static let fieldSage = Color(red: 0.2650, green: 0.3880, blue: 0.3257, opacity: 1)
        static let fieldSageFaint = Color(red: 0.2650, green: 0.3880, blue: 0.3257, opacity: 0.55)
        static let fieldSageFaintAlpha: Double = 0.55
        static let fieldGold = Color(red: 0.4586, green: 0.4061, blue: 0.2796, opacity: 1)
    }

    enum Spacing {
        static let xxxs: CGFloat = 2
        static let xxs: CGFloat = 4
        static let xs: CGFloat = 8
        static let sm: CGFloat = 12
        static let md: CGFloat = 16
        static let lg: CGFloat = 24
        static let xl: CGFloat = 40
        static let xxl: CGFloat = 64
        static let xxxl: CGFloat = 96
    }

    enum Radius {
        static let xs: CGFloat = 9.6
        static let sm: CGFloat = 15.2
        static let md: CGFloat = 20.8
        static let lg: CGFloat = 30.4
        static let xl: CGFloat = 41.6
        static let round: CGFloat = 15984
    }

    enum Duration {
        static let micro: TimeInterval = 0.11
        static let short: TimeInterval = 0.2
        static let medium: TimeInterval = 0.32
        static let long: TimeInterval = 0.5
        static let breathe: TimeInterval = 8.4
        static let drift: TimeInterval = 13
        static let ripple: TimeInterval = 3.2
    }
}
