import AVFoundation
import Foundation

/// The four bundled cues (spec: session-settings "Sound cues, all optional").
/// Original synthesized audio, generated by scripts/generate-sounds.mjs —
/// no third-party samples, no network.
enum SoundCue: String, CaseIterable {
    case focusTick, breakTick, focusEnd, breakEnd

    var resourceName: String {
        switch self {
        case .focusTick: "tick-focus.wav"
        case .breakTick: "tick-break.wav"
        case .focusEnd: "chime-focus-end.wav"
        case .breakEnd: "chime-break-end.wav"
        }
    }
}

/// The seam between sound policy (AppModel, tested) and audio machinery
/// (AVFoundation, inert in tests). A sound is presentation, never state.
protocol SoundCueScheduling {
    /// Arrange a one-shot chime for a future canonical instant.
    func scheduleChime(_ cue: SoundCue, at instant: Date, volume: Double)
    /// Withdraw every pending chime — the derivation it was based on changed.
    func cancelScheduledChimes()
    /// Start or stop a seamless tick loop. The loop is the audio file
    /// repeating, never a code timer.
    func setTickLoop(_ cue: SoundCue, running: Bool, volume: Double)
}

/// Production scheduler. Every failure path is silent by design: a missing
/// resource, a vanished output device, or a failed player must never
/// interrupt a session (spec: "Sound failure is silent, never fatal").
final class AudioCueScheduler: SoundCueScheduling {
    private let resourceLookup: (SoundCue) -> URL?
    private let clock: () -> Date = { Date() }
    private var pendingChimes: [AVAudioPlayer] = []
    private var tickPlayers: [SoundCue: AVAudioPlayer] = [:]

    init(
        resourceLookup: @escaping (SoundCue) -> URL? = { cue in
            Bundle.main.url(forResource: cue.resourceName, withExtension: nil, subdirectory: "Sounds")
                ?? Bundle.main.url(forResource: cue.resourceName, withExtension: nil)
        }
    ) {
        self.resourceLookup = resourceLookup
    }

    func scheduleChime(_ cue: SoundCue, at instant: Date, volume: Double) {
        guard let url = resourceLookup(cue), let player = try? AVAudioPlayer(contentsOf: url) else { return }
        // The one wall-clock read in this file: converting a canonical
        // engine instant into the audio device's own timebase. Allowlisted
        // in the module-wide clock scan; the delay is presentation lead
        // time, never session arithmetic.
        let delay = max(0, instant.timeIntervalSince(clock()))
        player.volume = Float(volume)
        player.prepareToPlay()
        player.play(atTime: player.deviceCurrentTime + delay)
        pendingChimes.append(player)
    }

    func cancelScheduledChimes() {
        pendingChimes.forEach { $0.stop() }
        pendingChimes.removeAll()
    }

    func setTickLoop(_ cue: SoundCue, running: Bool, volume: Double) {
        if running {
            guard tickPlayers[cue] == nil else {
                tickPlayers[cue]?.volume = Float(volume)
                return
            }
            guard let url = resourceLookup(cue), let player = try? AVAudioPlayer(contentsOf: url) else { return }
            player.numberOfLoops = -1
            player.volume = Float(volume)
            if player.play() { tickPlayers[cue] = player }
        } else {
            tickPlayers[cue]?.stop()
            tickPlayers[cue] = nil
        }
    }
}
