import AVFoundation
import Foundation
import os

/// The five bundled cues (spec: session-settings "Sound cues, all optional").
/// Original synthesized audio, generated by scripts/generate-sounds.mjs —
/// no third-party samples, no network.
enum SoundCue: String, CaseIterable {
    case blockStart, focusTick, breakTick, focusEnd, breakEnd

    var resourceName: String {
        switch self {
        case .blockStart: "chime-block-start.wav"
        case .focusTick: "tick-focus.wav"
        case .breakTick: "tick-break.wav"
        case .focusEnd: "chime-focus-end.wav"
        case .breakEnd: "chime-break-end.wav"
        }
    }
}

func shouldRetainChime(scheduledAt: Date, now: Date, isPlaying: Bool) -> Bool {
    isPlaying || scheduledAt > now
}

/// The seam between sound policy (AppModel, tested) and audio machinery
/// (AVFoundation, inert in tests). A sound is presentation, never state.
protocol SoundCueScheduling {
    /// Arrange a one-shot chime for a future canonical instant.
    func scheduleChime(_ cue: SoundCue, at instant: Date, volume: Double)
    /// Withdraw every pending chime — the derivation it was based on changed.
    func cancelScheduledChimes()
    /// Apply the master volume without interrupting in-flight one-shot cues.
    func setChimeVolume(_ volume: Double)
    /// Withdraw only chimes whose canonical instant has passed during sleep.
    func cancelExpiredChimes(at now: Date)
    /// Start or stop a seamless tick loop. The loop is the audio file
    /// repeating, never a code timer.
    func setTickLoop(_ cue: SoundCue, running: Bool, volume: Double)
}

/// Production scheduler. Every failure path is silent by design: a missing
/// resource, a vanished output device, or a failed player must never
/// interrupt a session (spec: "Sound failure is silent, never fatal").
final class AudioCueScheduler: SoundCueScheduling {
    private static let log = Logger(subsystem: "com.praxstack.praxmodoro", category: "sound")
    private let resourceLookup: (SoundCue) -> URL?
    private let clock: () -> Date
    private(set) var pendingChimes: [(player: AVAudioPlayer, scheduledAt: Date)] = []
    private var tickPlayers: [SoundCue: AVAudioPlayer] = [:]

    init(
        resourceLookup: @escaping (SoundCue) -> URL? = { cue in
            Bundle.main.url(forResource: cue.resourceName, withExtension: nil, subdirectory: "Sounds")
                ?? Bundle.main.url(forResource: cue.resourceName, withExtension: nil)
        },
        clock: @escaping () -> Date = { Date() }
    ) {
        self.resourceLookup = resourceLookup
        self.clock = clock
    }

    func scheduleChime(_ cue: SoundCue, at instant: Date, volume: Double) {
        let now = clock()
        // Finished players from past chimes are pruned here — the only
        // growth point — so the pending list cannot accumulate forever.
        pendingChimes.removeAll {
            !shouldRetainChime(scheduledAt: $0.scheduledAt, now: now, isPlaying: $0.player.isPlaying)
        }
        guard let url = resourceLookup(cue), let player = try? AVAudioPlayer(contentsOf: url) else {
            Self.log.debug("chime resource unavailable; staying silent")
            return
        }
        // The one wall-clock read in this file: converting a canonical
        // engine instant into the audio device's own timebase. Allowlisted
        // in the module-wide clock scan; the delay is presentation lead
        // time, never session arithmetic.
        let delay = max(0, instant.timeIntervalSince(now))
        player.volume = Float(volume)
        player.prepareToPlay()
        player.play(atTime: player.deviceCurrentTime + delay)
        pendingChimes.append((player, instant))
    }

    func cancelScheduledChimes() {
        pendingChimes.forEach { $0.player.stop() }
        pendingChimes.removeAll()
    }

    func setChimeVolume(_ volume: Double) {
        pendingChimes.forEach { $0.player.volume = Float(volume) }
    }

    func cancelExpiredChimes(at now: Date) {
        pendingChimes.removeAll {
            guard $0.scheduledAt <= now else { return false }
            $0.player.stop()
            return true
        }
    }

    func setTickLoop(_ cue: SoundCue, running: Bool, volume: Double) {
        if running {
            guard tickPlayers[cue] == nil else {
                tickPlayers[cue]?.volume = Float(volume)
                return
            }
            guard let url = resourceLookup(cue), let player = try? AVAudioPlayer(contentsOf: url) else {
                Self.log.debug("tick resource unavailable; staying silent")
                return
            }
            player.numberOfLoops = -1
            player.volume = Float(volume)
            if player.play() { tickPlayers[cue] = player }
        } else {
            tickPlayers[cue]?.stop()
            tickPlayers[cue] = nil
        }
    }
}
