#!/usr/bin/env bash
# Regenerate the Xcode project from app/project.yml. The .xcodeproj is a build
# artifact — never hand-edit it; edit project.yml and re-run this.
set -euo pipefail
cd "$(dirname "$0")/../app"

# Stamp build provenance (spec: app-scaffold). Generated file is gitignored.
sha=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
mkdir -p Sources/Generated
cat > Sources/Generated/BuildProvenance.swift <<EOF
// Generated by scripts/generate.sh — do not edit, do not commit.
enum BuildProvenance {
    static let version = "0.1.0"
    static let gitSHA = "${sha}"
    static let edition = "lite"
}
EOF

xcodegen generate
